<!ENTITY style-aeroways SYSTEM "predefined-style-aeroways.xml.inc">

<!ENTITY style-highways-fill SYSTEM "style-highways-fill.xml.inc">
<!ENTITY style-highways-casing SYSTEM "style-highways-casing.xml.inc">
<!ENTITY style-highways-fill-links SYSTEM "style-highways-fill-links.xml.inc">
<!ENTITY style-highways-casing-links SYSTEM "style-highways-casing-links.xml.inc">
<!ENTITY style-highways-area-fill SYSTEM "style-highways-area-fill.xml.inc">
<!ENTITY style-highways-area-casing SYSTEM "style-highways-area-casing.xml.inc">

<!ENTITY style-highways-fill-bridge SYSTEM "style-highways-fill-bridge.xml.inc">
<!ENTITY style-highways-casing-bridge SYSTEM "style-highways-casing-bridge.xml.inc">
<!ENTITY style-highways-fill-links-bridge SYSTEM "style-highways-fill-links-bridge.xml.inc">
<!ENTITY style-highways-casing-links-bridge SYSTEM "style-highways-casing-links-bridge.xml.inc">
<!ENTITY style-highways-area-fill-bridge SYSTEM "style-highways-area-fill-bridge.xml.inc">
<!ENTITY style-highways-area-casing-bridge SYSTEM "style-highways-area-casing-bridge.xml.inc">

<!ENTITY style-railways-fill SYSTEM "style-railways-fill.xml.inc">
