<Style name="style-highways-casing">
 <Rule>
  <MaxScaleDenominator>1225681</MaxScaleDenominator>
  <MinScaleDenominator>612840</MinScaleDenominator>
  <!-- z9 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">3</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>612840</MaxScaleDenominator>
  <MinScaleDenominator>306420</MinScaleDenominator>
  <!-- z10 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">3.3266270386</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>306420</MaxScaleDenominator>
  <MinScaleDenominator>153210</MinScaleDenominator>
  <!-- z11 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">3.9899405578</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>153210</MaxScaleDenominator>
  <MinScaleDenominator>76605</MinScaleDenominator>
  <!-- z12 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">4.9849108368</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>38302</MinScaleDenominator>
  <!-- z13 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">6.4773662551</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">8.7160493827</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">12.0740740741</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">17.1111111111</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">24.6666666667</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">36</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>1225681</MaxScaleDenominator>
  <MinScaleDenominator>612840</MinScaleDenominator>
  <!-- z9 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">3</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>612840</MaxScaleDenominator>
  <MinScaleDenominator>306420</MinScaleDenominator>
  <!-- z10 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">3.3266270386</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>306420</MaxScaleDenominator>
  <MinScaleDenominator>153210</MinScaleDenominator>
  <!-- z11 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">3.9899405578</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>153210</MaxScaleDenominator>
  <MinScaleDenominator>76605</MinScaleDenominator>
  <!-- z12 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">4.9849108368</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>38302</MinScaleDenominator>
  <!-- z13 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">6.4773662551</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">8.7160493827</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">12.0740740741</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">17.1111111111</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">24.6666666667</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'motorway' or [highway] = 'trunk') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">36</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>306420</MaxScaleDenominator>
  <MinScaleDenominator>153210</MinScaleDenominator>
  <!-- z11 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">3.8728852309</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>153210</MaxScaleDenominator>
  <MinScaleDenominator>76605</MinScaleDenominator>
  <!-- z12 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">4.8093278464</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>38302</MinScaleDenominator>
  <!-- z13 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">6.2139917695</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">8.3209876543</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">11.4814814815</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">16.2222222222</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">23.3333333333</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">34</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>306420</MaxScaleDenominator>
  <MinScaleDenominator>153210</MinScaleDenominator>
  <!-- z11 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">3.8728852309</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>153210</MaxScaleDenominator>
  <MinScaleDenominator>76605</MinScaleDenominator>
  <!-- z12 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">4.8093278464</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>38302</MinScaleDenominator>
  <!-- z13 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">6.2139917695</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">8.3209876543</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">11.4814814815</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">16.2222222222</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">23.3333333333</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'primary' or [highway] = 'primary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">34</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>153210</MaxScaleDenominator>
  <MinScaleDenominator>76605</MinScaleDenominator>
  <!-- z12 -->
  <Filter>
( ([highway] = 'secondary' or [highway] = 'secondary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">4.2825788752</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>38302</MinScaleDenominator>
  <!-- z13 -->
  <Filter>
( ([highway] = 'secondary' or [highway] = 'secondary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">5.4238683128</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
( ([highway] = 'secondary' or [highway] = 'secondary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">7.1358024691</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'secondary' or [highway] = 'secondary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">9.7037037037</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'secondary' or [highway] = 'secondary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">13.5555555556</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'secondary' or [highway] = 'secondary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">19.3333333333</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'secondary' or [highway] = 'secondary_link') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">28</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>153210</MaxScaleDenominator>
  <MinScaleDenominator>76605</MinScaleDenominator>
  <!-- z12 -->
  <Filter>
( ([highway] = 'secondary' or [highway] = 'secondary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">4.2825788752</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>38302</MinScaleDenominator>
  <!-- z13 -->
  <Filter>
( ([highway] = 'secondary' or [highway] = 'secondary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">5.4238683128</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
( ([highway] = 'secondary' or [highway] = 'secondary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">7.1358024691</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'secondary' or [highway] = 'secondary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">9.7037037037</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'secondary' or [highway] = 'secondary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">13.5555555556</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'secondary' or [highway] = 'secondary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">19.3333333333</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'secondary' or [highway] = 'secondary_link') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">28</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>38302</MinScaleDenominator>
  <!-- z13 -->
  <Filter>
( ([highway] = 'tertiary') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">4.8971193416</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
( ([highway] = 'tertiary') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">6.3456790123</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'tertiary') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">8.5185185185</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'tertiary') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">11.7777777778</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'tertiary') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">16.6666666667</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'tertiary') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">24</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>38302</MinScaleDenominator>
  <!-- z13 -->
  <Filter>
( ([highway] = 'tertiary') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">4.8971193416</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
( ([highway] = 'tertiary') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">6.3456790123</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'tertiary') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">8.5185185185</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'tertiary') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">11.7777777778</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'tertiary') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">16.6666666667</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'tertiary') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">24</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>38302</MinScaleDenominator>
  <!-- z13 -->
  <Filter>
( ([highway] = 'unclassified' or [highway] = 'road') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">4.633744856</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
( ([highway] = 'unclassified' or [highway] = 'road') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">5.950617284</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'unclassified' or [highway] = 'road') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">7.9259259259</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'unclassified' or [highway] = 'road') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">10.8888888889</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'unclassified' or [highway] = 'road') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">15.3333333333</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'unclassified' or [highway] = 'road') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">22</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>38302</MinScaleDenominator>
  <!-- z13 -->
  <Filter>
( ([highway] = 'unclassified' or [highway] = 'road') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">4.633744856</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
( ([highway] = 'unclassified' or [highway] = 'road') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">5.950617284</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'unclassified' or [highway] = 'road') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">7.9259259259</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'unclassified' or [highway] = 'road') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">10.8888888889</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'unclassified' or [highway] = 'road') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">15.3333333333</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'unclassified' or [highway] = 'road') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">22</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
( ([highway] = 'residential') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">5.1604938272</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'residential') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">6.7407407407</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'residential') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">9.1111111111</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'residential') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">12.6666666667</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'residential') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">18</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
( ([highway] = 'residential') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">5.1604938272</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'residential') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">6.7407407407</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'residential') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">9.1111111111</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'residential') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">12.6666666667</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'residential') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">18</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'service') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">4</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'trigger_cycleForbidden') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">4</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'service') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">4.6666666667</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'service') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">6</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'service') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">8</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'service') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">4</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'trigger_cycleForbidden') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">4</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'service') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">4.6666666667</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'service') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">6</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'service') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">8</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'living_street') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">6.1481481481</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'living_street') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">8.2222222222</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'living_street') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">11.3333333333</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'living_street') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">16</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'living_street') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">6.1481481481</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'living_street') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">8.2222222222</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'living_street') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">11.3333333333</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'living_street') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">16</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'pedestrian') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">4.962962963</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'pedestrian') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">6.4444444444</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'pedestrian') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">8.6666666667</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'pedestrian') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">12</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'pedestrian') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">4.962962963</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'pedestrian') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">6.4444444444</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'pedestrian') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">8.6666666667</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'pedestrian') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">12</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z13 - z14 -->
  <Filter>
( ([highway] = 'trigger_cycleForbidden') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">1</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'trigger_cycleForbidden') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">1.1851851852</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'trigger_cycleForbidden') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">1.7777777778</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'trigger_cycleForbidden') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">2.6666666667</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z13 - z14 -->
  <Filter>
( ([highway] = 'trigger_cycleForbidden') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">1</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'trigger_cycleForbidden') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">1.1851851852</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'trigger_cycleForbidden') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">1.7777777778</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'trigger_cycleForbidden') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">2.6666666667</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z13 - z14 -->
  <Filter>
( ([highway] = 'track' or [highway] = 'path' or [highway] = 'bridleway') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">1</CssParameter>
   <CssParameter name="stroke">#988243</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'track' or [highway] = 'path' or [highway] = 'bridleway') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">1.1851851852</CssParameter>
   <CssParameter name="stroke">#988243</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'track' or [highway] = 'path' or [highway] = 'bridleway') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">1.7777777778</CssParameter>
   <CssParameter name="stroke">#988243</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'track' or [highway] = 'path' or [highway] = 'bridleway') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">2.6666666667</CssParameter>
   <CssParameter name="stroke">#988243</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'track' or [highway] = 'path' or [highway] = 'bridleway') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">4</CssParameter>
   <CssParameter name="stroke">#988243</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z13 - z14 -->
  <Filter>
( ([highway] = 'track' or [highway] = 'path' or [highway] = 'bridleway') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">1</CssParameter>
   <CssParameter name="stroke">#988243</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'track' or [highway] = 'path' or [highway] = 'bridleway') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">1.1851851852</CssParameter>
   <CssParameter name="stroke">#988243</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'track' or [highway] = 'path' or [highway] = 'bridleway') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">1.7777777778</CssParameter>
   <CssParameter name="stroke">#988243</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'track' or [highway] = 'path' or [highway] = 'bridleway') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">2.6666666667</CssParameter>
   <CssParameter name="stroke">#988243</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'track' or [highway] = 'path' or [highway] = 'bridleway') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">4</CssParameter>
   <CssParameter name="stroke">#988243</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z13 - z14 -->
  <Filter>
( ([highway] = 'steps') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">1</CssParameter>
   <CssParameter name="stroke">#f1eee8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'steps') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">1.1851851852</CssParameter>
   <CssParameter name="stroke">#f1eee8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'steps') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">1.7777777778</CssParameter>
   <CssParameter name="stroke">#f1eee8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'steps') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">2.6666666667</CssParameter>
   <CssParameter name="stroke">#f1eee8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'steps') and ( 
 not ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke-width">4</CssParameter>
   <CssParameter name="stroke">#f1eee8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z13 - z14 -->
  <Filter>
( ([highway] = 'steps') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">1</CssParameter>
   <CssParameter name="stroke">#f1eee8</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( ([highway] = 'steps') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">1.1851851852</CssParameter>
   <CssParameter name="stroke">#f1eee8</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( ([highway] = 'steps') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">1.7777777778</CssParameter>
   <CssParameter name="stroke">#f1eee8</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( ([highway] = 'steps') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">2.6666666667</CssParameter>
   <CssParameter name="stroke">#f1eee8</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( ([highway] = 'steps') and ( 
 ([tunnel] = 'yes' or [tunnel] = 'true' or [tunnel] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linejoin">round</CssParameter>
   <CssParameter name="stroke-linecap">butt</CssParameter>
   <CssParameter name="stroke-width">4</CssParameter>
   <CssParameter name="stroke">#f1eee8</CssParameter>
   <CssParameter name="stroke-dasharray">8,8</CssParameter>
  </LineSymbolizer>
 </Rule>
</Style>
