<Style name="style-highways-cycle-casing">
 <Rule>
  <MaxScaleDenominator>153210</MaxScaleDenominator>
  <MinScaleDenominator>76605</MinScaleDenominator>
  <!-- z12 -->
  <Filter>
([highway] = 'trigger_cycleway')</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke">#009c27</CssParameter>
   <CssParameter name="stroke-width">1</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>38302</MinScaleDenominator>
  <!-- z13 -->
  <Filter>
([highway] = 'trigger_cycleway')</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke">#009c27</CssParameter>
   <CssParameter name="stroke-width">1.0534979424</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
([highway] = 'trigger_cycleway')</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke">#009c27</CssParameter>
   <CssParameter name="stroke-width">1.5802469136</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
([highway] = 'trigger_cycleway')</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke">#009c27</CssParameter>
   <CssParameter name="stroke-width">2.3703703704</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
([highway] = 'trigger_cycleway')</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke">#009c27</CssParameter>
   <CssParameter name="stroke-width">3.5555555556</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
([highway] = 'trigger_cycleway')</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke">#009c27</CssParameter>
   <CssParameter name="stroke-width">5.3333333333</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
([highway] = 'trigger_cycleway')</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke">#009c27</CssParameter>
   <CssParameter name="stroke-width">8</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>153210</MaxScaleDenominator>
  <MinScaleDenominator>76605</MinScaleDenominator>
  <!-- z12 -->
  <Filter>
([highway] = 'trigger_cycleAllowed')</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-width">3</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>38302</MinScaleDenominator>
  <!-- z13 -->
  <Filter>
([highway] = 'trigger_cycleAllowed')</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-width">3.0534979424</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
([highway] = 'trigger_cycleAllowed')</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-width">3.5802469136</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
([highway] = 'trigger_cycleAllowed')</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-width">4.3703703704</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
([highway] = 'trigger_cycleAllowed')</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-width">5.5555555556</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
([highway] = 'trigger_cycleAllowed')</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-width">7.3333333333</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
([highway] = 'trigger_cycleAllowed')</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke-linecap">round</CssParameter>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-width">10</CssParameter>
  </LineSymbolizer>
 </Rule>
</Style>
