<Style name="style-highways-cycle-casing-bridge">
 <Rule>
  <MaxScaleDenominator>153210</MaxScaleDenominator>
  <MinScaleDenominator>76605</MinScaleDenominator>
  <!-- z12 -->
  <Filter>
( (([highway] = 'cycleway' or ([highway] = 'footway' and [bicycle] = 'compulsory') or ([highway] = 'path' and [bicycle] = 'compulsory') or ([public_transport] = 'platform' and [bicycle] = 'compulsory'))) and ( 
  ([bridge] = 'yes' or [bridge] = 'true' or [bridge] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke">#333333</CssParameter>
   <CssParameter name="stroke-width">3</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>38302</MinScaleDenominator>
  <!-- z13 -->
  <Filter>
( (([highway] = 'cycleway' or ([highway] = 'footway' and [bicycle] = 'compulsory') or ([highway] = 'path' and [bicycle] = 'compulsory') or ([public_transport] = 'platform' and [bicycle] = 'compulsory'))) and ( 
  ([bridge] = 'yes' or [bridge] = 'true' or [bridge] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke">#333333</CssParameter>
   <CssParameter name="stroke-width">3.0534979424</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
( (([highway] = 'cycleway' or ([highway] = 'footway' and [bicycle] = 'compulsory') or ([highway] = 'path' and [bicycle] = 'compulsory') or ([public_transport] = 'platform' and [bicycle] = 'compulsory'))) and ( 
  ([bridge] = 'yes' or [bridge] = 'true' or [bridge] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke">#333333</CssParameter>
   <CssParameter name="stroke-width">3.5802469136</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( (([highway] = 'cycleway' or ([highway] = 'footway' and [bicycle] = 'compulsory') or ([highway] = 'path' and [bicycle] = 'compulsory') or ([public_transport] = 'platform' and [bicycle] = 'compulsory'))) and ( 
  ([bridge] = 'yes' or [bridge] = 'true' or [bridge] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke">#333333</CssParameter>
   <CssParameter name="stroke-width">4.3703703704</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( (([highway] = 'cycleway' or ([highway] = 'footway' and [bicycle] = 'compulsory') or ([highway] = 'path' and [bicycle] = 'compulsory') or ([public_transport] = 'platform' and [bicycle] = 'compulsory'))) and ( 
  ([bridge] = 'yes' or [bridge] = 'true' or [bridge] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke">#333333</CssParameter>
   <CssParameter name="stroke-width">5.5555555556</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( (([highway] = 'cycleway' or ([highway] = 'footway' and [bicycle] = 'compulsory') or ([highway] = 'path' and [bicycle] = 'compulsory') or ([public_transport] = 'platform' and [bicycle] = 'compulsory'))) and ( 
  ([bridge] = 'yes' or [bridge] = 'true' or [bridge] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke">#333333</CssParameter>
   <CssParameter name="stroke-width">7.3333333333</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( (([highway] = 'cycleway' or ([highway] = 'footway' and [bicycle] = 'compulsory') or ([highway] = 'path' and [bicycle] = 'compulsory') or ([public_transport] = 'platform' and [bicycle] = 'compulsory'))) and ( 
  ([bridge] = 'yes' or [bridge] = 'true' or [bridge] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke">#333333</CssParameter>
   <CssParameter name="stroke-width">10</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>153210</MaxScaleDenominator>
  <MinScaleDenominator>76605</MinScaleDenominator>
  <!-- z12 -->
  <Filter>
( (((((([access] = 'allowed' or [access] = 'compulsory') and not [bicycle] = 'forbidden')) or (([access] = 'forbidden' or [highway] = 'footway') and ([bicycle] = 'allowed' or [bicycle] = 'compulsory'))) and (([highway] = 'footway' and [bicycle] = 'allowed') or ([highway] = 'path' and ([surface] = 'paved' or [surface] = 'concrete' or [surface] = 'asphalt' or [tracktype] = 'grade1') ) or ([highway] = 'track' and ([surface] = 'paved' or [surface] = 'concrete' or [surface] = 'asphalt' or [tracktype] = 'grade1'))))) and ( 
  ([bridge] = 'yes' or [bridge] = 'true' or [bridge] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-width">3</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>76605</MaxScaleDenominator>
  <MinScaleDenominator>38302</MinScaleDenominator>
  <!-- z13 -->
  <Filter>
( (((((([access] = 'allowed' or [access] = 'compulsory') and not [bicycle] = 'forbidden')) or (([access] = 'forbidden' or [highway] = 'footway') and ([bicycle] = 'allowed' or [bicycle] = 'compulsory'))) and (([highway] = 'footway' and [bicycle] = 'allowed') or ([highway] = 'path' and ([surface] = 'paved' or [surface] = 'concrete' or [surface] = 'asphalt' or [tracktype] = 'grade1') ) or ([highway] = 'track' and ([surface] = 'paved' or [surface] = 'concrete' or [surface] = 'asphalt' or [tracktype] = 'grade1'))))) and ( 
  ([bridge] = 'yes' or [bridge] = 'true' or [bridge] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke">#bababa</CssParameter>
   <CssParameter name="stroke-width">3.0534979424</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>38302</MaxScaleDenominator>
  <MinScaleDenominator>19151</MinScaleDenominator>
  <!-- z14 -->
  <Filter>
( (((((([access] = 'allowed' or [access] = 'compulsory') and not [bicycle] = 'forbidden')) or (([access] = 'forbidden' or [highway] = 'footway') and ([bicycle] = 'allowed' or [bicycle] = 'compulsory'))) and (([highway] = 'footway' and [bicycle] = 'allowed') or ([highway] = 'path' and ([surface] = 'paved' or [surface] = 'concrete' or [surface] = 'asphalt' or [tracktype] = 'grade1') ) or ([highway] = 'track' and ([surface] = 'paved' or [surface] = 'concrete' or [surface] = 'asphalt' or [tracktype] = 'grade1'))))) and ( 
  ([bridge] = 'yes' or [bridge] = 'true' or [bridge] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke">#595959</CssParameter>
   <CssParameter name="stroke-width">3.5802469136</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>19151</MaxScaleDenominator>
  <MinScaleDenominator>9575</MinScaleDenominator>
  <!-- z15 -->
  <Filter>
( (((((([access] = 'allowed' or [access] = 'compulsory') and not [bicycle] = 'forbidden')) or (([access] = 'forbidden' or [highway] = 'footway') and ([bicycle] = 'allowed' or [bicycle] = 'compulsory'))) and (([highway] = 'footway' and [bicycle] = 'allowed') or ([highway] = 'path' and ([surface] = 'paved' or [surface] = 'concrete' or [surface] = 'asphalt' or [tracktype] = 'grade1') ) or ([highway] = 'track' and ([surface] = 'paved' or [surface] = 'concrete' or [surface] = 'asphalt' or [tracktype] = 'grade1'))))) and ( 
  ([bridge] = 'yes' or [bridge] = 'true' or [bridge] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke">#595959</CssParameter>
   <CssParameter name="stroke-width">4.3703703704</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>9575</MaxScaleDenominator>
  <MinScaleDenominator>4787</MinScaleDenominator>
  <!-- z16 -->
  <Filter>
( (((((([access] = 'allowed' or [access] = 'compulsory') and not [bicycle] = 'forbidden')) or (([access] = 'forbidden' or [highway] = 'footway') and ([bicycle] = 'allowed' or [bicycle] = 'compulsory'))) and (([highway] = 'footway' and [bicycle] = 'allowed') or ([highway] = 'path' and ([surface] = 'paved' or [surface] = 'concrete' or [surface] = 'asphalt' or [tracktype] = 'grade1') ) or ([highway] = 'track' and ([surface] = 'paved' or [surface] = 'concrete' or [surface] = 'asphalt' or [tracktype] = 'grade1'))))) and ( 
  ([bridge] = 'yes' or [bridge] = 'true' or [bridge] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke">#595959</CssParameter>
   <CssParameter name="stroke-width">5.5555555556</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>4787</MaxScaleDenominator>
  <MinScaleDenominator>2393</MinScaleDenominator>
  <!-- z17 -->
  <Filter>
( (((((([access] = 'allowed' or [access] = 'compulsory') and not [bicycle] = 'forbidden')) or (([access] = 'forbidden' or [highway] = 'footway') and ([bicycle] = 'allowed' or [bicycle] = 'compulsory'))) and (([highway] = 'footway' and [bicycle] = 'allowed') or ([highway] = 'path' and ([surface] = 'paved' or [surface] = 'concrete' or [surface] = 'asphalt' or [tracktype] = 'grade1') ) or ([highway] = 'track' and ([surface] = 'paved' or [surface] = 'concrete' or [surface] = 'asphalt' or [tracktype] = 'grade1'))))) and ( 
  ([bridge] = 'yes' or [bridge] = 'true' or [bridge] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke">#595959</CssParameter>
   <CssParameter name="stroke-width">7.3333333333</CssParameter>
  </LineSymbolizer>
 </Rule>
 <Rule>
  <MaxScaleDenominator>2393</MaxScaleDenominator>
  <!-- z18 -->
  <Filter>
( (((((([access] = 'allowed' or [access] = 'compulsory') and not [bicycle] = 'forbidden')) or (([access] = 'forbidden' or [highway] = 'footway') and ([bicycle] = 'allowed' or [bicycle] = 'compulsory'))) and (([highway] = 'footway' and [bicycle] = 'allowed') or ([highway] = 'path' and ([surface] = 'paved' or [surface] = 'concrete' or [surface] = 'asphalt' or [tracktype] = 'grade1') ) or ([highway] = 'track' and ([surface] = 'paved' or [surface] = 'concrete' or [surface] = 'asphalt' or [tracktype] = 'grade1'))))) and ( 
  ([bridge] = 'yes' or [bridge] = 'true' or [bridge] = '1') )
)</Filter>
  <LineSymbolizer>
   <CssParameter name="stroke">#595959</CssParameter>
   <CssParameter name="stroke-width">10</CssParameter>
  </LineSymbolizer>
 </Rule>
</Style>
